import type { NextPage } from 'next';
import { useEffect } from 'react';
import Head from 'next/head';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import Sidemenu from '@/components/sidemenu';
import MainContent from '@/components/mainContent';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/navigation';
import { gitHubProfile, gitHubRepositories } from '@/store/githubAccountSlice';
import { AppDispatch } from '@/store/store';
import { useDispatch } from 'react-redux';

interface HomeProps {
  githubUsername?: string;
}

const Home: NextPage<HomeProps> = ({
  githubUsername,
}: HomeProps) => {
  const dispatch = useDispatch<AppDispatch>();
  const router = useRouter();

  useEffect(() => {
    const username = githubUsername || 'octocat'
    dispatch(gitHubProfile({ githubUsername: username }))
    .then((res: any) => {
      if (!res.payload.status) {
        router.push('/');
      }
    });

    dispatch(gitHubRepositories({ githubUsername: username }))
  }, []);

  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Simple.Repo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="max-w-6xl mx-auto grid grid-cols-4 gap-4 px-5 pb-10">
          <div className="col-span-4 md:col-span-1">
            <Sidemenu />
          </div>
          <div className="col-span-4 md:col-span-3">
            <MainContent />
          </div>
        </main>
      </div>
      <Footer />
    </>
  );
};

export default Home;
