name: simple-repo-deployment

on:
  push:
    branches:
      - master
      - main
      - staging

env:
  PROJECT_ID: ${{ vars.CLOUD_RUN_PROJECT_NAME }}
  REGION: asia-southeast1
  SERVICE_NAME_FRONT_END: testing-deploying-fe
  SERVICE_NAME_BACK_END: testing-deploying-be

jobs:
  front-end-service:
    name: Frontend Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        run: |-
          cd frontend
          docker build . --tag gcr.io/$PROJECT_ID/$SERVICE_NAME_FRONT_END:$GITHUB_SHA

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME_FRONT_END:$GITHUB_SHA

      - name: Declare some variables
        shell: bash
        run: |
          echo "GITHUB_ENV=$(git rev-parse "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.SERVICE_NAME_FRONT_END }}
          image: "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME_FRONT_END }}:${{ env.GITHUB_ENV }}"
          region: ${{ env.REGION }}

  back-end-service:
    name: Backend Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        run: |-
          cd backend
          docker build . --tag gcr.io/$PROJECT_ID/$SERVICE_NAME_BACK_END:$GITHUB_SHA

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME_BACK_END:$GITHUB_SHA

      - name: Declare some variables
        shell: bash
        run: |
          echo "GITHUB_ENV=$(git rev-parse "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.SERVICE_NAME_BACK_END }}
          image: "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME_BACK_END }}:${{ env.GITHUB_ENV }}"
          region: ${{ env.REGION }}
          env_vars: |
            APP_ENV=PRODUCTION
            GITHUB_OAUTH_CLIENT_ID=${{ vars.PRODUCTION_GITHUB_OAUTH_CLIENT_ID }}
            GITHUB_OAUTH_CLIENT_SECRET=${{ secrets.PRODUCTION_GITHUB_OAUTH_CLIENT_SECRET }}
            JWT_SECRET=${{ secrets.PRODUCTION_JWT_SECRET }}
